### ISSUE TITLE
Slow display and "Connection timeout; please refresh to try again"

### ISSUE THREAD

**Issue by tealc210** [audreyt/ethercalc#302]
Hello, I've got those 2 problems when accessing/modifying a spreadsheet.
The installation have been made on Ubuntu Jessie.
Redis version is 2.8.4-2, and node-js is 0.10.25.
I have verified the redis configuration, and the timeout is disabled (timeout 0).
With this, the modifications made aren't saved, I have to try again and again and hope that no timeout will come.
This happened after access of any Multi-sheet document. A restart of ethercalc is necessary.
If I need to access a sheet on /=my-doc without problem, I need to go to /my-doc.1, /my-doc.2, etc...
I don't understand where is the problem... Do you have any hint?

**Comment by ldidry** [comment]
When you need to restart ethercalc, is there an ethercalc that is using 100% of a CPU? If yes, is killing this thread unblock ethercalc?

I have a similar problem, but it doesn't happen each time i go to a multi-sheet document. In fact, I'm not able to reproduce my problem, it just happens like every two days or less. We (Framasoft, an association I work for, which provides the ethercalc service for anyone who want to use it) have a lot of users and calcs and we can't be sure that someone isn't using a multi-sheet doc when the crash happens.

**Comment by audreyt** [comment]
Hi @ldidry, did you upgrade to webworker-threads 0.7.1 ? yufeih put a fix to that that I have not yet got time to test on ethercalc.org

**Comment by ldidry** [comment]
@audreyt No, I'm using ww-t 0.6.3. I'm using the ethercalc npmjs package (0.20160210.0). Do you think it can be safe to upgrade ww-t only?

**Comment by audreyt** [comment]
Yes. The only change is the removal of `freeThreadsQueue` which may cause the spinning you mentioned.

**Comment by audreyt** [comment]
Hi, to make everybody's live easier to upgrade I've just rolled out ethercalc@0.20160307.0 :-)

**Comment by audreyt** [comment]
Also, with this release it should be (theoretically) OK to use latest stable Node versions (after the iojs merge, that is). If someone would like to try on a larger installation please let me know the result.

**Comment by ldidry** [comment]
I upgraded our Ethercalc to the latest release (0.20160307.0 + my patch of #251) with an upgrade of NodeJs to 4.4.0 and it's, for now, working well, without any CPU-burning blocking thread.

Let's wait a week or two before saying the problem is definitely solved?

**Comment by audreyt** [comment]
OK. I have published 0.20160314.0 (with your patch) to ethercalc.org and so far looking good.

**Comment by tealc210** [comment]
Hi, their is no difference for me. I've installed a new Ubuntu VM, with nodejs 4.4.0 and redis 2.8.4, installed ethercalc on it, and the problem still remains, but the CPU is OK. Is their a preffered distribution of Linux to use?

**Comment by ldidry** [comment]
I use Debian, but maybe your problem isn't the same that mine. Just an idea: what web server do you use? Is it websocket-compliant ? (and its configuration too)

**Comment by tealc210** [comment]
For now, I'm not using any webserver. I just send the requests on the
ethercalc default port.
Else, I would use Apache HTTPD, with more or less the same configuration
proposed in the project.

2016-03-17 18:02 GMT+01:00 Luc Didry <notifications@github.com>:
