### ISSUE TITLE
=TEXTBOX loses focus after each keystroke

### ISSUE THREAD

**Issue by audreyt** [audreyt/ethercalc#383]
@eddyparkinson Hi! I was documenting the forms interface, and discovered that while  http://sheet.cellmaster.com.au/yoyoform_h4x46rujd0yv/app works fine, https://ethercalc.org/yoyoform_6jlcgs7qbrjv/app loses inputbox cursor focus after each keystroke (tested: Safari, Firefox) — also tested on local ethercalc instance with the same issue.

Would you like to investigate a bit at your convenience?

**Comment by eddyparkinson** [comment]
I thought I merged the fix for the focus issues. I will look at it, maybe I still need to push something.

I am hoping in about 2 weeks I will have some time to sync my version with yours, as Marcel also made a restructure change that will take time to sync, so it is not just a simple push.

**Comment by eddyparkinson** [comment]
should be fixed #410

**Comment by rolandwillis** [comment]
@audreyt @eddyparkinson Hi. I think there is still an issue here. Consider http://ethercalc.org/roland/form and http://ethercalc.org/roland2/form (you can replace ethercalc with sheet.cellmaster.com.au too as I created the same forms on both sites to compare) . When the textbox fields are in the first column there is a problem with focus. When the textbox fields are located elsewhere in the sheet, the focus works as expected.
Now on my local copy of Ethercalc installed with npm i -g ethercalc, I get the focus problem no matter where I put the textboxes. I can only fix it by taking your copies of ./static/ethercalc.js (from either ethercalc.org or sheet.cellmaster.com.au) and overwriting my local static/ethercalc.js with the source, but of course the problem with textboxes being in the first column still occurs. Incidentally I tried the docker image as well but the local problem exists with that distribution too. If I can be of any further help with testing please let me know.

**Comment by eddyparkinson** [comment]
Roland,

>When the textbox fields are in the first column there is a problem with focus
Yes, you are right - not sure when I will fix it.  The workaround is to avoid using Col "A".

=AUTOCOMPLETE()
There is also a bug with autocomplete box, it needs to get focus twice because the first time it loads the list of items and drops the focus when it loads them.
 
Eddy.

**Comment by eddyparkinson** [comment]
@rolandwillis what is your use case - what are you using the texbox etc for?

**Comment by rolandwillis** [comment]
Hi Eddy,

I am writing an MVC app in C# using an HttpClient to fetch content from an Ethercalc instance. All security and room management is done within MVC e.g. a user logs in and creates a room with a friendly name e.g. 'Quarter 3 Financials' by uploading an Xlsx document. The Mvc app checks that the logged in user has an Author role, generates a guid and posts the binary data to /_/{guid} or if no binary data supplied then posts room and snapshot command fields to /_
.If the post is successful then the guid is stored in a SQL database along with the friendly name etc. The user can then manage a Room Access list to deny or grant other users access explicitly.
The users are a bunch of smart finance guys who will squeeze every last drop of functionality out of Ethercalc and I have to make sure that if there are any bugs with Ethercalc itself that I understand them fully. I can now give instructions to the effect of 'dont use column A for textboxes as it is a known bug.'
The short answer therefore is 'No specific use case'.
Thanks again for all the hard work!
