### ISSUE TITLE
Copy/Paste multiple cell with at least 1 formula result in reference miscalculation

### ISSUE THREAD

**Issue by superedo73** [audreyt/ethercalc#491]
Hello,
if I write 1  in A1 ,  2 in A2  and  =A1+A2   in  A3   it shows   the result value 3 as expected.

Then, if I select and copy the 3 cells and paste from B1  ,   in B3  the formula traslate to =B3+B4 instead of =B1+B2  as expected , showing a "Circular reference to B3" 

This happens with all types of cut/paste operations via clipboard involving cells with formulas

**Comment by eddyparkinson** [comment]
Sorry, but I am not able to replicate this.  
I tried -
  A1: 1
 A2: 2
  A3: =A1+A2

A3 shows 3 as expected.
select A1:A3 and paste in B1 using Ctrl+c and Ctrl+v
B3 has =B1+B2 as expected

also
select A1:A3 and paste in B1 using tool bar
B3 has =B1+B2 as expected

also
select A1:A3 and paste in B1 using round fill tool (shows wien mouse is over blue dot)
B3 has =B1+B2 as expected


I have been using the copy and paste for a few year, never seen any bugs with it.
How old it the version you are using?

**Comment by eddyparkinson** [comment]
**Fix**

This looks like the fix, - is it in your version
https://github.com/eddyparkinson/socialcalc/commit/caf107134536953aa4da4a5ea05e0e10f492ceba

Same bug?
https://github.com/audreyt/ethercalc/issues/261

**Comment by superedo73** [comment]
Sorry, I see the same behaviour also with the fix indicated.

In my particular case I use loadclipboard  +  past  to preload a simple sheet with formulas on an instance of sheet, but the paste itself recalculate and misplace the formulas (this procedure worked perfectly on older/official version of Socialcalc).

**Comment by eddyparkinson** [comment]
My fault.  https://github.com/eddyparkinson/socialcalc/commit/caf107134536953aa4da4a5ea05e0e10f492ceba caused the multi cell paste to fail. 
Copy one cell to many is now fixed, But copy and paste many cells now fails :(

**Comment by baby-gnu** [comment]
The issue is still present, steps to reproduce:

* click on *Clipboard* menu
* select *SocialCalc-save format*
* paste the following lines
```
version:1.5
cell:A1:v:1
cell:B1:v:1
cell:C1:vtf:n:2:SUM(A1\cB1)
cell:A2:v:2
cell:B2:v:2
cell:C2:vtf:n:4:SUM(A2\cB2)
cell:A3:v:3
cell:B3:v:3
cell:C3:vtf:n:6:SUM(A3\cB3)
cell:C4:vtf:n:10:SUM(C2\cC3)
col:R:w:149
sheet:c:18:r:4:tvf:1
valueformat:1:text-wiki
copiedfrom:A1:C4
```
* click on *Load SocialCalc Clipboard With This*
* got to an empty cell
* click on the *Paste* button

The resulted pasted content is now:

```
version:1.5
cell:A1:v:1
cell:B1:v:1
cell:C1:vtf:n:2:SUM(C1\cD1):e:Circular reference to C1
cell:A2:v:2
cell:B2:v:2
cell:C2:vtf:n:0:SUM(C3\cD3)
cell:A3:v:3
cell:B3:v:3
cell:C3:vtf:n:0:SUM(C5\cD5)
cell:C4:vtf:n:0:SUM(E5\cE6)
col:R:w:149
sheet:c:18:r:4:circularreferencecell:C1|C1:tvf:1
valueformat:1:text-wiki
copiedfrom:A1:C4
```

Regards.

**Comment by eddyparkinson** [comment]
Pull requests welcome. I would also like this bug fixed.
